### ISSUE TITLE
保活不生效

### ISSUE THREAD

**Issue by zhangxujia** [Pangu-Immortal/KeepAlivePerfect#12]

**Comment by 15198184721** [comment]
这个项目本来就是不生效的。生效的是不开源的。付费的。应该不便宜反正

**Comment by amduwcwt** [comment]
失效而且付费，付了几万打水漂了

---- 回复的原邮件 ----
| 发件人 | Small ***@***.***> |
| 发送日期 | 2024年02月21日 14:16 |
| 收件人 | Pangu-Immortal/KeepAlivePerfect ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [Pangu-Immortal/KeepAlivePerfect] 保活不生效 (Issue #12) |

这个项目本来就是不生效的。生效的是不开源的。付费的。应该不便宜反正

**Comment by 15198184721** [comment]
我也问过之前。就是说的按个收费！多少钱一个。估计升级了又要重新给钱多半是！而且吧感觉这个开源项目每次更新都是更新的说明。估计也没想开源的都


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月21日(周三) 下午2:21
收件人: ***@***.***&gt;;
抄送: &quot;Small ***@***.******@***.***&gt;;
主题: Re: [Pangu-Immortal/KeepAlivePerfect] 保活不生效 (Issue #12)




 失效而且付费，付了几万打水漂了
 
 ---- 回复的原邮件 ----
 | 发件人 | Small ***@***.***&gt; |
 | 发送日期 | 2024年02月21日 14:16 |
 | 收件人 | Pangu-Immortal/KeepAlivePerfect ***@***.***&gt; |
 | 抄送人 | Subscribed ***@***.***&gt; |
 | 主题 | Re: [Pangu-Immortal/KeepAlivePerfect] 保活不生效 (Issue #12) |
 
 这个项目本来就是不生效的。生效的是不开源的。付费的。应该不便宜反正
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; 
&mdash;
